// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $enhanced_one from "./routes/enhanced/one.ts";
import * as $enhanced_wasm from "./routes/enhanced/wasm.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/enhanced/one.ts": $enhanced_one,
    "./routes/enhanced/wasm.ts": $enhanced_wasm,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
