// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $enhance_js from "./routes/enhance-js.ts";
import * as $enhance_wasm from "./routes/enhance-wasm.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/enhance-js.ts": $enhance_js,
    "./routes/enhance-wasm.ts": $enhance_wasm,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
